let OSTYPE = system('uname')

" release autogroup in MyAutoCmd
augroup MyAutoCmd
  autocmd!
augroup END

set t_Co=256

source ~/.vim/vimrc_sets
source ~/.vim/vimrc_keymaps
source ~/.vim/vimrc_plugins

" Load settings for each location.
augroup vimrc-local
  autocmd!
  autocmd BufNewFile,BufReadPost * call s:vimrc_local(expand('<afile>:p:h'))
augroup END

function! s:vimrc_local(loc)
  let files = findfile('.vimrc.local', escape(a:loc, ' ') . ';', -1)
  for i in reverse(filter(files, 'filereadable(v:val)'))
    source `=i`
  endfor
endfunction

nnoremap ; :
nnoremap : ;
