export PATH=/usr/local/go/bin:$HOME/dotfiles/forpath:$HOME/Dropbox/forpath:$PATH:/usr/share/doc/git/contrib/diff-highlight:$PATH
export GOROOT=/usr/local/go
export GOPATH=$HOME/work/mygo

case "${OSTYPE}" in
darwin*)
    export PATH=/opt/local/bin:/opt/local/sbin:$PATH
    export MANPATH=/opt/local/man:$MANPATH
    export PATH=/opt/local/share/git-core/contrib/diff-highlight:$PATH
    export GOROOT=/opt/local/go/
    ;;
esac

#ruby rbenv
if [ -d $HOME/.rbenv ] ; then
    export PATH=$HOME/.rbenv/bin:$PATH
    eval "$(rbenv init - zsh)"
    alias be='bundle exec'
fi
