source $ZDOTDIR/zprezto_zshenv
alias tmux='TERM=screen-256color tmux'

#ruby rbenv
if [ -d ${HOME}/.rbenv  ] ; then
    export PATH=${HOME}/.rbenv/bin:${HOME}/.rbenv/shims:${PATH}
    eval "$(rbenv init -)"
    alias be='bundle exec'
fi
