export TERM=xterm-256color
export PATH=/usr/share/doc/git/contrib/diff-highlight:$PATH
export PATH=~/dotfiles/forpath:~/Dropbox/forpath:$PATH
export PATH=/opt/local/share/git-core/contrib/diff-highlight:$PATH
