export PATH=/usr/share/doc/git/contrib/diff-highlight:$PATH
export PATH=~/dotfiles/forpath:~/Dropbox/forpath:$PATH
export PATH=/opt/local/share/git-core/contrib/diff-highlight:$PATH
alias tmux='TERM=screen-256color tmux'
