# include antigen settings
source $HOME/dotfiles/zsh/zshrc.antigen
#export VTE_CJK_WIDTH=1

alias -g G='| grep'
alias -g L='| less'
alias -g H='| head'
alias -g T='| tail'
alias -g S='| sort'
alias -g W='| wc'
alias -g XG='| xargs grep'

case "${OSTYPE}" in
# Linux
linux*)
     # python virtualenv
    if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
        export WORKON_HOME=$HOME/.virtualenvs
        source /usr/local/bin/virtualenvwrapper.sh
    fi
    ;;
# Mac(Unix)
darwin*)
    # Customize to your needs...
    PATH=$PATH:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin
    export PATH
    PYTHON_VER=2.7
    export MACPORTS_PREFIX=/opt/local
    export MANPATH=/opt/local/man:$MANPATH
    export PYTHONPATH=$MACPORTS_PREFIX/lib/python$PYTHON_VER/:$PYTHONPATH
    export VIRTUALENV_BIN=$MACPORTS_PREFIX/Library/Frameworks/Python.framework/Versions/$PYTHON_VER
    # python virtualenv
    if [ -e $VIRTUALENV_BIN/bin/virtualenvwrapper.sh ] ; then
        #export VIRTUALENVWRAPPER_VIRTUALENV=$VIRTUALENV_BIN/bin/virtualenv
        export WORKON_HOME=$HOME/.virtualenvs
        $VIRTUALENV_BIN/bin/virtualenvwrapper.sh
    fi
    ;;
esac

#SimpleHTTPServer
shttps (){
    python -m SimpleHTTPServer $1
}
# multi version python virtualenv
mkvenv () {
    base_python=`which python$1`
    mkvirtualenv --distribute --python=$base_python $2
}

#z.sh settings
if [ ! -d $HOME/dotfiles/zsh/z ] ; then
    cd $HOME/dotfiles/zsh
    git clone https://github.com/rupa/z.git
fi
_Z_CMD=j
source $HOME/dotfiles/zsh/z/z.sh
precmd() {
    _z --add "$(pwd -P)"
}

#Nodejs
if [ -d $HOME/.nvm ] ; then
    source $HOME/.nvm/nvm.sh
    nvm use v0.11.13
fi

export PROMPT="$PROMPT"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")'

[[ -z "$TMUX" ]] && TERM=screen-256color tmux

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
